### ISSUE TITLE
s3 repo format

### ISSUE THREAD

**Issue by AnthonyWC** [szinck/s3apt#1]
I followed your article http://webscale.plumbing/managing-apt-repos-in-s3-using-lambda

but s3 repo format doesn't seem to work?

I followed similar format:
```
s3 repo in /etc/apt/sources.list.d/s3repo.list
deb s3://my-bucket-name/  dists/webscale.plumbing/2.0/
```

I made a prod folder with version path; I see the Packages and deb file in the folder.

Run apt-get update:
```
Error code is
W: Failed to fetch s3://sample-s3-repo.amazonaws.com/dists/prod/3.8/Packages  403  Forbidden
```
From what I can see the difference between deb-s3 (which works) is that deb-s3 generates a Releases file whereas this method doesn't.  You mention that you need to reindex, how is that trigger (within the lambda?)

**Comment by jportasa** [comment]
@AnthonyWC Trigger is defined in the Lambda through AWS console. I see that the repo structure is not the standard one, is a custom structure of repos. If you use it for example for debian standard repo, doesn't work because the directories are different :-(

**Comment by AnthonyWC** [comment]
That post was from 4 years ago; pretty sure I either fixed it or used something else. :P
